import {
  MinionIconFill1,
  MinionIconFill2,
  MinionIconFill3,
  MinionIconFill4,
  MinionIconFill5,
  MinionIconFill6,
  MinionIconFill7,
  MinionIconFill8,
  MinionIconFill9,
  MinionIconFill10,
  MinionIconFill11,
  MinionIconFill12,
  MinionIconOutline1,
  MinionIconOutline10,
  MinionIconOutline12,
  MinionIconOutline2,
  MinionIconOutline3,
  MinionIconOutline4,
  MinionIconOutline5,
  MinionIconOutline6,
  MinionIconOutline7,
  MinionIconOutline9,
} from './ui/Icons';

export const ALL_MINION_ICONS_FILL = [
  MinionIconFill1,
  MinionIconFill2,
  MinionIconFill3,
  MinionIconFill4,
  MinionIconFill5,
  MinionIconFill6,
  MinionIconFill7,
  MinionIconFill8,
  MinionIconFill9,
  MinionIconFill10,
  MinionIconFill11,
  MinionIconFill12,
];

export const ALL_MINION_ICONS_OUTLINE = [
  MinionIconOutline1,
  MinionIconOutline2,
  MinionIconOutline3,
  MinionIconOutline4,
  MinionIconOutline5,
  MinionIconOutline6,
  MinionIconOutline7,
  MinionIconOutline9,
  MinionIconOutline10,
  MinionIconOutline12,
];
