# side note - you can test this locally with act (https://github.com/nektos/act)
name: minions CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          # based on the package.json file engine.node
          node-version: '18.x'
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - run: yarn lint
